// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.1
// source: gbProto.proto

package gbp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid string `protobuf:"bytes,1,opt,name=Tid,proto3" json:"Tid,omitempty"`
	Sid string `protobuf:"bytes,2,opt,name=Sid,proto3" json:"Sid,omitempty"`
	Msg string `protobuf:"bytes,3,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *ChatPayload) Reset() {
	*x = ChatPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPayload) ProtoMessage() {}

func (x *ChatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPayload.ProtoReflect.Descriptor instead.
func (*ChatPayload) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{0}
}

func (x *ChatPayload) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *ChatPayload) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *ChatPayload) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type Transport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg []byte `protobuf:"bytes,1,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Id  string `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Tp  int32  `protobuf:"varint,3,opt,name=Tp,proto3" json:"Tp,omitempty"`
}

func (x *Transport) Reset() {
	*x = Transport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{1}
}

func (x *Transport) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Transport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transport) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

type MsgFormat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid  string `protobuf:"bytes,1,opt,name=Sid,proto3" json:"Sid,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Mloc string `protobuf:"bytes,3,opt,name=Mloc,proto3" json:"Mloc,omitempty"`
}

func (x *MsgFormat) Reset() {
	*x = MsgFormat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgFormat) ProtoMessage() {}

func (x *MsgFormat) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgFormat.ProtoReflect.Descriptor instead.
func (*MsgFormat) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{2}
}

func (x *MsgFormat) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *MsgFormat) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *MsgFormat) GetMloc() string {
	if x != nil {
		return x.Mloc
	}
	return ""
}

type RecvNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId string `protobuf:"bytes,1,opt,name=UId,proto3" json:"UId,omitempty"`
	MId string `protobuf:"bytes,2,opt,name=MId,proto3" json:"MId,omitempty"`
	Tp  int32  `protobuf:"varint,3,opt,name=Tp,proto3" json:"Tp,omitempty"`
}

func (x *RecvNotify) Reset() {
	*x = RecvNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecvNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecvNotify) ProtoMessage() {}

func (x *RecvNotify) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecvNotify.ProtoReflect.Descriptor instead.
func (*RecvNotify) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{3}
}

func (x *RecvNotify) GetUId() string {
	if x != nil {
		return x.UId
	}
	return ""
}

func (x *RecvNotify) GetMId() string {
	if x != nil {
		return x.MId
	}
	return ""
}

func (x *RecvNotify) GetTp() int32 {
	if x != nil {
		return x.Tp
	}
	return 0
}

type ClientName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UId string `protobuf:"bytes,1,opt,name=UId,proto3" json:"UId,omitempty"`
	MId string `protobuf:"bytes,2,opt,name=MId,proto3" json:"MId,omitempty"`
}

func (x *ClientName) Reset() {
	*x = ClientName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientName) ProtoMessage() {}

func (x *ClientName) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientName.ProtoReflect.Descriptor instead.
func (*ClientName) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{4}
}

func (x *ClientName) GetUId() string {
	if x != nil {
		return x.UId
	}
	return ""
}

func (x *ClientName) GetMId() string {
	if x != nil {
		return x.MId
	}
	return ""
}

type SendNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TMid string `protobuf:"bytes,1,opt,name=TMid,proto3" json:"TMid,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *SendNotify) Reset() {
	*x = SendNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotify) ProtoMessage() {}

func (x *SendNotify) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotify.ProtoReflect.Descriptor instead.
func (*SendNotify) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{5}
}

func (x *SendNotify) GetTMid() string {
	if x != nil {
		return x.TMid
	}
	return ""
}

func (x *SendNotify) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ChatAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MId  string `protobuf:"bytes,1,opt,name=MId,proto3" json:"MId,omitempty"`
	MLoc string `protobuf:"bytes,2,opt,name=MLoc,proto3" json:"MLoc,omitempty"`
}

func (x *ChatAck) Reset() {
	*x = ChatAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gbProto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatAck) ProtoMessage() {}

func (x *ChatAck) ProtoReflect() protoreflect.Message {
	mi := &file_gbProto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatAck.ProtoReflect.Descriptor instead.
func (*ChatAck) Descriptor() ([]byte, []int) {
	return file_gbProto_proto_rawDescGZIP(), []int{6}
}

func (x *ChatAck) GetMId() string {
	if x != nil {
		return x.MId
	}
	return ""
}

func (x *ChatAck) GetMLoc() string {
	if x != nil {
		return x.MLoc
	}
	return ""
}

var File_gbProto_proto protoreflect.FileDescriptor

var file_gbProto_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x67, 0x62, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x43, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x50, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x54, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x54, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x3d, 0x0a, 0x09, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x70, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x54, 0x70, 0x22, 0x43, 0x0a, 0x09, 0x4d, 0x73, 0x67,
	0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x53, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x53, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x6c,
	0x6f, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x6c, 0x6f, 0x63, 0x22, 0x40,
	0x0a, 0x0a, 0x52, 0x65, 0x63, 0x76, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x4d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x49, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x54, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x54, 0x70,
	0x22, 0x30, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x55, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x49, 0x64, 0x22, 0x34, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x4d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x54, 0x4d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x74,
	0x41, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x4c, 0x6f, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x4c, 0x6f, 0x63, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x67,
	0x62, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gbProto_proto_rawDescOnce sync.Once
	file_gbProto_proto_rawDescData = file_gbProto_proto_rawDesc
)

func file_gbProto_proto_rawDescGZIP() []byte {
	file_gbProto_proto_rawDescOnce.Do(func() {
		file_gbProto_proto_rawDescData = protoimpl.X.CompressGZIP(file_gbProto_proto_rawDescData)
	})
	return file_gbProto_proto_rawDescData
}

var file_gbProto_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_gbProto_proto_goTypes = []interface{}{
	(*ChatPayload)(nil), // 0: main.ChatPayload
	(*Transport)(nil),   // 1: main.Transport
	(*MsgFormat)(nil),   // 2: main.MsgFormat
	(*RecvNotify)(nil),  // 3: main.RecvNotify
	(*ClientName)(nil),  // 4: main.ClientName
	(*SendNotify)(nil),  // 5: main.SendNotify
	(*ChatAck)(nil),     // 6: main.ChatAck
}
var file_gbProto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gbProto_proto_init() }
func file_gbProto_proto_init() {
	if File_gbProto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gbProto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Transport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgFormat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecvNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gbProto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gbProto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gbProto_proto_goTypes,
		DependencyIndexes: file_gbProto_proto_depIdxs,
		MessageInfos:      file_gbProto_proto_msgTypes,
	}.Build()
	File_gbProto_proto = out.File
	file_gbProto_proto_rawDesc = nil
	file_gbProto_proto_goTypes = nil
	file_gbProto_proto_depIdxs = nil
}
